go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
go test -run ^Test_server_NetPipe_errorKey$ >> errorKey.txt
