// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: packOper_pro.proto

package gspackoper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//type packOper struct {
//OperType uint8
//OperData []byte
//Data     []byte
//Rand     []byte
//HashHex  []byte
//}
type packOperPro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperType uint32 `protobuf:"varint,1,opt,name=OperType,proto3" json:"OperType,omitempty"`
	OperData []byte `protobuf:"bytes,2,opt,name=OperData,proto3" json:"OperData,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Rand     []byte `protobuf:"bytes,4,opt,name=Rand,proto3" json:"Rand,omitempty"`
	HashHex  []byte `protobuf:"bytes,5,opt,name=HashHex,proto3" json:"HashHex,omitempty"`
}

func (x *packOperPro) Reset() {
	*x = packOperPro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packOper_pro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *packOperPro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*packOperPro) ProtoMessage() {}

func (x *packOperPro) ProtoReflect() protoreflect.Message {
	mi := &file_packOper_pro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use packOperPro.ProtoReflect.Descriptor instead.
func (*packOperPro) Descriptor() ([]byte, []int) {
	return file_packOper_pro_proto_rawDescGZIP(), []int{0}
}

func (x *packOperPro) GetOperType() uint32 {
	if x != nil {
		return x.OperType
	}
	return 0
}

func (x *packOperPro) GetOperData() []byte {
	if x != nil {
		return x.OperData
	}
	return nil
}

func (x *packOperPro) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *packOperPro) GetRand() []byte {
	if x != nil {
		return x.Rand
	}
	return nil
}

func (x *packOperPro) GetHashHex() []byte {
	if x != nil {
		return x.HashHex
	}
	return nil
}

var File_packOper_pro_proto protoreflect.FileDescriptor

var file_packOper_pro_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x61, 0x63, 0x6b, 0x4f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x73, 0x70, 0x61, 0x63, 0x6b, 0x6f, 0x70, 0x65, 0x72,
	0x22, 0x88, 0x01, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x4f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x4f, 0x70, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x4f, 0x70, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x52, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x52, 0x61, 0x6e,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x48, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x48, 0x61, 0x73, 0x68, 0x48, 0x65, 0x78, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x3b, 0x67, 0x73, 0x70, 0x61, 0x63, 0x6b, 0x6f, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packOper_pro_proto_rawDescOnce sync.Once
	file_packOper_pro_proto_rawDescData = file_packOper_pro_proto_rawDesc
)

func file_packOper_pro_proto_rawDescGZIP() []byte {
	file_packOper_pro_proto_rawDescOnce.Do(func() {
		file_packOper_pro_proto_rawDescData = protoimpl.X.CompressGZIP(file_packOper_pro_proto_rawDescData)
	})
	return file_packOper_pro_proto_rawDescData
}

var file_packOper_pro_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packOper_pro_proto_goTypes = []interface{}{
	(*packOperPro)(nil), // 0: gspackoper.packOper_pro
}
var file_packOper_pro_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packOper_pro_proto_init() }
func file_packOper_pro_proto_init() {
	if File_packOper_pro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packOper_pro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*packOperPro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packOper_pro_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packOper_pro_proto_goTypes,
		DependencyIndexes: file_packOper_pro_proto_depIdxs,
		MessageInfos:      file_packOper_pro_proto_msgTypes,
	}.Build()
	File_packOper_pro_proto = out.File
	file_packOper_pro_proto_rawDesc = nil
	file_packOper_pro_proto_goTypes = nil
	file_packOper_pro_proto_depIdxs = nil
}
